target_config_table: "yahoofina"
source_information:
  source_system: "yahoofina"
  target_schema: "bronze_yahoofina"
object_information:

  - source_table: "MSFT"
    target_table: "msft"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "AAPL"
    target_table: "aapl"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "GOOGL"
    target_table: "googl"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "AMZN"
    target_table: "amzn"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "META"
    target_table: "meta"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ORCL"
    target_table: "orcl"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ADBE"
    target_table: "adbe"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "CRM"
    target_table: "crm"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "INTU"
    target_table: "intu"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "SNOW"
    target_table: "snow"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "SAP"
    target_table: "sap"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "NOW"
    target_table: "now"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "IBM"
    target_table: "ibm"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "CSCO"
    target_table: "csco"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "DELL"
    target_table: "dell"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "WDAY"
    target_table: "wday"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ADSK"
    target_table: "adsk"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "TWLO"
    target_table: "twlo"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "SQ"
    target_table: "sq"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "SHOP"
    target_table: "shop"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ZM"
    target_table: "zm"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "DBX"
    target_table: "dbx"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ZS"
    target_table: "zs"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "TEAM"
    target_table: "team"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "TWTR"
    target_table: "twtr"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "TSM"
    target_table: "tsm"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "TXN"
    target_table: "txn"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ASML"
    target_table: "asml"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "MU"
    target_table: "mu"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "NXPI"
    target_table: "nxpi"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ADP"
    target_table: "adp"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ADI"
    target_table: "adi"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "DOCU"
    target_table: "docu"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "PLTR"
    target_table: "pltr"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "CRWD"
    target_table: "crwd"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "NET"
    target_table: "net"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "OKTA"
    target_table: "okta"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "RNG"
    target_table: "rng"
    load_type: "incremental"
    incremental_key: "date"








    