target_config_table: "yahoofina"
source_information:
  source_system: "yahoofina"
  target_schema: "bronze_yahoofina"
object_information:

  - source_table: "MSFT"
    target_table: "msft"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "AAPL"
    target_table: "aapl"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "GOOGL"
    target_table: "googl"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "AMZN"
    target_table: "amzn"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "META"
    target_table: "meta"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ORCL"
    target_table: "orcl"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ADBE"
    target_table: "adbe"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "CRM"
    target_table: "crm"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "INTU"
    target_table: "intu"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "SNOW"
    target_table: "snow"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "SAP"
    target_table: "sap"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "NOW"
    target_table: "now"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "IBM"
    target_table: "ibm"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "CSCO"
    target_table: "csco"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "DELL"
    target_table: "dell"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "WDAY"
    target_table: "wday"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ADSK"
    target_table: "adsk"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "TWLO"
    target_table: "twlo"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "SQ"
    target_table: "sq"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "SHOP"
    target_table: "shop"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ZM"
    target_table: "zm"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "DBX"
    target_table: "dbx"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ZS"
    target_table: "zs"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "TEAM"
    target_table: "team"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "TWTR"
    target_table: "twtr"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "TSM"
    target_table: "tsm"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "TXN"
    target_table: "txn"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ASML"
    target_table: "asml"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "MU"
    target_table: "mu"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "NXPI"
    target_table: "nxpi"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ADP"
    target_table: "adp"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "ADI"
    target_table: "adi"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "DOCU"
    target_table: "docu"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "PLTR"
    target_table: "pltr"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "CRWD"
    target_table: "crwd"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "NET"
    target_table: "net"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "OKTA"
    target_table: "okta"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "RNG"
    target_table: "rng"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"








    