target_config_table: "quandlfina"
source_information:
  source_system: "quandlfina"
  api_key: "MvDgQDhTTE8sMYYegoz_"
  target_schema: "bronze_quandlfina"
  source_database: "WIKI"
object_information:

  - source_table: "AMD"
    target_table: "amd"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "NVDA"
    target_table: "nvda"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "INTC"
    target_table: "intc"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "QCOM"
    target_table: "qcom"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "AVGO"
    target_table: "avgo"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "LRCX"
    target_table: "lrcx"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "AMAT"
    target_table: "amat"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "CDNS"
    target_table: "cdns"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "FTNT"
    target_table: "ftnt"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "PANW"
    target_table: "panw"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "MRVL"
    target_table: "mrvl"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "SPLK"
    target_table: "splk"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "HUBS"
    target_table: "hubs"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "NTNX"
    target_table: "ntnx"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"

  - source_table: "DDOG"
    target_table: "ddog"
    primary_key: "source_table, date"
    load_type: "incremental"
    incremental_key: "date"



